import {ThemeContext, ThemeProvider} from '@/context/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { useContext } from 'react'
import { Header } from '@/components/Header'
import { Analytics } from '@vercel/analytics/react'

export const metadata: Metadata = {
  title: "Henry's Portfolio",
  description: 'Generated by HenryCodeT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
          <Header/>
          <main>
            {children}
            <Analytics />
          </main>  
      </ThemeProvider>
    </html>
  )
}
